# Generated by Django 4.2.7 on 2025-10-03 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('workflow_type', models.CharField(choices=[('incident_approval', 'Aprobación de Incidencia'), ('document_approval', 'Aprobación de Documento'), ('quality_review', 'Revisión de Calidad'), ('supplier_response', 'Respuesta de Proveedor'), ('escalation', 'Escalación'), ('custom', 'Personalizado')], max_length=50, verbose_name='Tipo de Workflow')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_default', models.BooleanField(default=False, verbose_name='Por Defecto')),
                ('auto_start', models.BooleanField(default=False, verbose_name='Inicio Automático')),
                ('allow_parallel', models.BooleanField(default=False, verbose_name='Permitir Pasos Paralelos')),
                ('max_duration', models.DurationField(blank=True, null=True, verbose_name='Duración Máxima')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de Workflow',
                'verbose_name_plural': 'Plantillas de Workflow',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('step_type', models.CharField(choices=[('approval', 'Aprobación'), ('review', 'Revisión'), ('notification', 'Notificación'), ('assignment', 'Asignación'), ('escalation', 'Escalación'), ('condition', 'Condición'), ('action', 'Acción')], max_length=50, verbose_name='Tipo de Paso')),
                ('order', models.PositiveIntegerField(verbose_name='Orden')),
                ('is_required', models.BooleanField(default=True, verbose_name='Requerido')),
                ('is_parallel', models.BooleanField(default=False, verbose_name='Paralelo')),
                ('time_limit', models.DurationField(blank=True, null=True, verbose_name='Tiempo Límite')),
                ('auto_advance', models.BooleanField(default=False, verbose_name='Avance Automático')),
                ('assigned_to_role', models.CharField(blank=True, max_length=50, verbose_name='Rol Asignado')),
                ('assigned_to_group', models.CharField(blank=True, max_length=50, verbose_name='Grupo Asignado')),
                ('condition_expression', models.TextField(blank=True, verbose_name='Expresión de Condición')),
                ('action_script', models.TextField(blank=True, verbose_name='Script de Acción')),
                ('notify_on_start', models.BooleanField(default=True, verbose_name='Notificar al Iniciar')),
                ('notify_on_complete', models.BooleanField(default=True, verbose_name='Notificar al Completar')),
                ('notify_on_timeout', models.BooleanField(default=True, verbose_name='Notificar al Vencimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asignado')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.workflowtemplate')),
            ],
            options={
                'verbose_name': 'Paso de Workflow',
                'verbose_name_plural': 'Pasos de Workflow',
                'ordering': ['template', 'order'],
                'unique_together': {('template', 'order')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('rule_type', models.CharField(choices=[('auto_start', 'Inicio Automático'), ('auto_approve', 'Aprobación Automática'), ('auto_reject', 'Rechazo Automático'), ('auto_escalate', 'Escalación Automática'), ('auto_notify', 'Notificación Automática'), ('auto_assign', 'Asignación Automática')], max_length=50, verbose_name='Tipo de Regla')),
                ('condition_expression', models.TextField(verbose_name='Expresión de Condición')),
                ('action_script', models.TextField(verbose_name='Script de Acción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Prioridad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_workflow_rules', to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.workflowstep', verbose_name='Paso de Workflow')),
                ('workflow_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.workflowtemplate', verbose_name='Plantilla de Workflow')),
            ],
            options={
                'verbose_name': 'Regla de Workflow',
                'verbose_name_plural': 'Reglas de Workflow',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_incident_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_document_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado'), ('timeout', 'Tiempo Agotado')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_workflows', to=settings.AUTH_USER_MODEL)),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflowstep', verbose_name='Paso Actual')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_workflows', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='workflows.workflowtemplate')),
            ],
            options={
                'verbose_name': 'Instancia de Workflow',
                'verbose_name_plural': 'Instancias de Workflow',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('started', 'Iniciado'), ('step_started', 'Paso Iniciado'), ('step_completed', 'Paso Completado'), ('step_rejected', 'Paso Rechazado'), ('step_delegated', 'Paso Delegado'), ('step_timeout', 'Paso Vencido'), ('workflow_completed', 'Workflow Completado'), ('workflow_rejected', 'Workflow Rechazado'), ('workflow_cancelled', 'Workflow Cancelado'), ('workflow_timeout', 'Workflow Vencido')], max_length=50)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='workflows.workflowinstance')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflowstep')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Workflow',
                'verbose_name_plural': 'Historial de Workflows',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('delegated', 'Delegado')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True, verbose_name='Comentarios')),
                ('justification', models.TextField(blank=True, verbose_name='Justificación')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_approvals', to=settings.AUTH_USER_MODEL)),
                ('delegated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_approvals', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='workflows.workflowinstance')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='workflows.workflowstep')),
            ],
            options={
                'verbose_name': 'Aprobación de Workflow',
                'verbose_name_plural': 'Aprobaciones de Workflow',
                'ordering': ['-assigned_at'],
                'unique_together': {('instance', 'step', 'approver')},
            },
        ),
    ]
