# Generated by Django 4.2.7 on 2025-10-07 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de notificación',
                'verbose_name_plural': 'Categorías de notificaciones',
                'db_table': 'notification_categories',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('web_enabled', models.BooleanField(default=True)),
                ('incident_created', models.BooleanField(default=True)),
                ('incident_updated', models.BooleanField(default=True)),
                ('incident_escalated', models.BooleanField(default=True)),
                ('incident_closed', models.BooleanField(default=True)),
                ('document_uploaded', models.BooleanField(default=True)),
                ('document_approved', models.BooleanField(default=True)),
                ('document_rejected', models.BooleanField(default=True)),
                ('workflow_step_completed', models.BooleanField(default=True)),
                ('workflow_approval_required', models.BooleanField(default=True)),
                ('system_alert', models.BooleanField(default=True)),
                ('user_assigned', models.BooleanField(default=True)),
                ('deadline_approaching', models.BooleanField(default=True)),
                ('deadline_exceeded', models.BooleanField(default=True)),
                ('priority_threshold', models.CharField(choices=[('all', 'Todas'), ('medium_up', 'Media y superior'), ('high_up', 'Alta y superior'), ('urgent_only', 'Solo urgentes')], default='all', max_length=20)),
                ('notification_start_time', models.TimeField(default='09:00')),
                ('notification_end_time', models.TimeField(default='18:00')),
                ('quiet_hours', models.BooleanField(default=True)),
                ('weekend_notifications', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_important', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('notification_type', models.CharField(choices=[('incident_created', 'Incidencia Creada'), ('incident_updated', 'Incidencia Actualizada'), ('incident_escalated', 'Incidencia Escalada'), ('incident_closed', 'Incidencia Cerrada'), ('document_uploaded', 'Documento Subido'), ('document_approved', 'Documento Aprobado'), ('document_rejected', 'Documento Rechazado'), ('workflow_step_completed', 'Paso de Workflow Completado'), ('workflow_approval_required', 'Aprobación de Workflow Requerida'), ('system_alert', 'Alerta del Sistema'), ('user_assigned', 'Usuario Asignado'), ('deadline_approaching', 'Fecha Límite Próxima'), ('deadline_exceeded', 'Fecha Límite Excedida'), ('quality_report_submitted', 'Reporte de Calidad Enviado'), ('quality_report_approved', 'Reporte de Calidad Aprobado'), ('quality_report_rejected', 'Reporte de Calidad Rechazado'), ('visit_report_submitted', 'Reporte de Visita Enviado'), ('visit_report_approved', 'Reporte de Visita Aprobado'), ('visit_report_rejected', 'Reporte de Visita Rechazado')], max_length=50)),
                ('related_url', models.URLField(blank=True, max_length=500, null=True)),
                ('related_incident_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_document_id', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_notifications', to='notifications.notificationcategory')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notifications',
                'indexes': [models.Index(fields=['-created_at'], name='notificatio_created_8fa075_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'), models.Index(fields=['user', 'is_important'], name='notificatio_user_id_3d15ad_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx'), models.Index(fields=['category'], name='notificatio_categor_0d96ae_idx')],
            },
        ),
    ]
