# Generated by Django 4.2.7 on 2025-10-07 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreferences',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='notificationpreferences',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notification_notifica_2a4584_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notification_user_id_d4c27a_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notification_categor_1b5f3a_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_notifications', to='notifications.notificationcategory'),
        ),
        migrations.DeleteModel(
            name='NotificationPreferences',
        ),
    ]
