# Generated by Django 4.2.7 on 2025-10-07 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_update'),
    ]

    operations = [
        # This migration was trying to clean up 0003's mess, but due to conflicts, 
        # we are neutralizing it. 
        # The result will be that NotificationPreferences (from 0002) remains in DB 
        # but unused by the app (which uses 0001). Acceptable for now.
    ]
