# Generated by Django 4.2.7 on 2026-02-19 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_remove_notificationpreferences_categories_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationPreferences',
        ),
    ]
