# Generated by Django 4.2.7 on 2026-04-24 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Rol del usuario (clave única)', max_length=50, unique=True)),
                ('permissions', models.JSONField(default=dict, help_text='Diccionario de permisos (acciones)')),
                ('accessible_pages', models.JSONField(default=list, help_text='Lista de páginas accesibles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permiso de Rol',
                'verbose_name_plural': 'Permisos de Roles',
                'db_table': 'role_permissions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(help_text='Nombre de usuario único', max_length=150, unique=True)),
                ('email', models.EmailField(db_index=True, help_text='Email del usuario', max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, help_text='Nombre del usuario', max_length=150)),
                ('last_name', models.CharField(blank=True, help_text='Apellido del usuario', max_length=150)),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('management', 'Gerencia'), ('technical_service', 'Servicio Técnico'), ('quality', 'Calidad'), ('supervisor', 'Supervisor Postventa'), ('analyst', 'Analista Técnico'), ('customer_service', 'Atención al Cliente'), ('provider', 'Proveedor')], db_index=True, default='analyst', help_text='Rol del usuario en el sistema', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el usuario está activo')),
                ('is_staff', models.BooleanField(default=False, help_text='Indica si el usuario puede acceder al admin')),
                ('is_superuser', models.BooleanField(default=False, help_text='Indica si el usuario es superusuario')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de registro')),
                ('last_login', models.DateTimeField(blank=True, help_text='Último inicio de sesión', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del usuario')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
                ('phone', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20)),
                ('department', models.CharField(blank=True, help_text='Departamento o área de trabajo', max_length=100)),
                ('digital_signature', models.ImageField(blank=True, help_text='Imagen de la firma digital del usuario', null=True, upload_to='users/signatures/', verbose_name='Firma Digital')),
                ('sap_user', models.CharField(blank=True, help_text='Usuario de SAP Service Layer para transacciones', max_length=100, null=True)),
                ('sap_password', models.CharField(blank=True, help_text='Contraseña de SAP Service Layer (se almacena para el login automático)', max_length=255, null=True)),
                ('permissions_override', models.JSONField(blank=True, default=dict, help_text='Sobrescritura de permisos específicos para este usuario')),
                ('pages_override', models.JSONField(blank=True, default=list, help_text='Sobrescritura de páginas accesibles para este usuario')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'users',
                'permissions': [],
                'default_permissions': (),
            },
        ),
    ]
