# Generated by Django 4.2.7 on 2025-10-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_groups_remove_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('management', 'Gerencia'), ('technical_service', 'Servicio Técnico'), ('quality', 'Calidad'), ('supervisor', 'Supervisor Postventa'), ('analyst', 'Analista Técnico'), ('customer_service', 'Atención al Cliente'), ('provider', 'Proveedor')], default='analyst', help_text='Rol del usuario en el sistema', max_length=20),
        ),
    ]
