# Generated by Django 4.2.7 on 2025-12-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, help_text='Email del usuario', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('management', 'Gerencia'), ('technical_service', 'Servicio Técnico'), ('quality', 'Calidad'), ('supervisor', 'Supervisor Postventa'), ('analyst', 'Analista Técnico'), ('customer_service', 'Atención al Cliente'), ('provider', 'Proveedor')], db_index=True, default='analyst', help_text='Rol del usuario en el sistema', max_length=20),
        ),
    ]
