# Generated by Django 4.2.7 on 2026-01-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_email_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='digital_signature',
            field=models.ImageField(blank=True, help_text='Imagen de la firma digital del usuario', null=True, upload_to='users/signatures/', verbose_name='Firma Digital'),
        ),
    ]
