# Generated by Django 4.2.7 on 2026-02-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Rol del usuario (clave única)', max_length=50, unique=True)),
                ('permissions', models.JSONField(default=dict, help_text='Diccionario de permisos (acciones)')),
                ('accessible_pages', models.JSONField(default=list, help_text='Lista de páginas accesibles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permiso de Rol',
                'verbose_name_plural': 'Permisos de Roles',
                'db_table': 'role_permissions',
            },
        ),
    ]
