# Generated by Django 4.2.7 on 2026-03-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sap_password',
            field=models.CharField(blank=True, help_text='Contraseña de SAP Service Layer (se almacena para el login automático)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sap_user',
            field=models.CharField(blank=True, help_text='Usuario de SAP Service Layer para transacciones', max_length=100, null=True),
        ),
    ]
