# Generated by Django 4.2.7 on 2026-03-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_sap_password_user_sap_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pages_override',
            field=models.JSONField(blank=True, default=list, help_text='Sobrescritura de páginas accesibles para este usuario'),
        ),
        migrations.AddField(
            model_name='user',
            name='permissions_override',
            field=models.JSONField(blank=True, default=dict, help_text='Sobrescritura de permisos específicos para este usuario'),
        ),
    ]
