# Generated by Django 4.2.7 on 2025-10-03 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('api_key', models.CharField(max_length=500)),
                ('base_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1)),
                ('requests_per_minute', models.IntegerField(default=60)),
                ('requests_per_day', models.IntegerField(default=1000)),
                ('cost_per_token', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor de IA',
                'verbose_name_plural': 'Proveedores de IA',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('image_analysis', 'Análisis de Imagen'), ('document_analysis', 'Análisis de Documento'), ('technical_report', 'Informe Técnico'), ('quality_inspection', 'Inspección de Calidad')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('input_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('input_description', models.TextField(blank=True, null=True)),
                ('ai_provider', models.CharField(default='openai', max_length=100)),
                ('model_used', models.CharField(default='gpt-4o', max_length=100)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('processed_analysis', models.TextField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('generated_report', models.TextField(blank=True, null=True)),
                ('report_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análisis de IA',
                'verbose_name_plural': 'Análisis de IA',
                'ordering': ['-created_at'],
            },
        ),
    ]
