# Generated by Django 4.2.7 on 2026-04-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_login', 'Iniciar Sesión'), ('user_logout', 'Cerrar Sesión'), ('incident_created', 'Incidente Creado'), ('incident_closed', 'Incidente Cerrado'), ('escalation_triggered', 'Incidente Escalado'), ('report_attached', 'Reporte Adjuntado'), ('report_created', 'Reporte Creado'), ('report_updated', 'Reporte Editado'), ('create', 'Crear'), ('update', 'Actualizar'), ('delete', 'Eliminar'), ('item_restored', 'Elemento Restaurado'), ('sap_sync_error', 'Fallo Sincronización SAP'), ('pdf_error', 'Error en Generación de PDF'), ('api_error', 'Error de Integración API')], db_index=True, max_length=50, verbose_name='Acción')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Detalles Adicionales')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='Dirección IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y Hora')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeletedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.CharField(help_text='ID original del objeto', max_length=255)),
                ('model_name', models.CharField(help_text='Nombre del modelo (ej. Incident)', max_length=100)),
                ('app_label', models.CharField(help_text='App del modelo (ej. incidents)', max_length=100)),
                ('serialized_data', models.JSONField(help_text='Datos completos del objeto en formato JSON')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('restore_deadline', models.DateTimeField(db_index=True)),
                ('object_repr', models.CharField(default='Elemento eliminado', help_text='Representación legible del objeto', max_length=255)),
                ('deletion_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Elemento Eliminado',
                'verbose_name_plural': 'Elementos Eliminados (Papelera)',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
