# Generated by Django 4.2.7 on 2025-10-08 18:46
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Iniciar Sesión'), ('logout', 'Cerrar Sesión'), ('crear', 'Crear'), ('actualizar', 'Actualizar'), ('eliminar', 'Eliminar'), ('ver', 'Ver'), ('subir', 'Subir Archivo'), ('descargar', 'Descargar Archivo'), ('escalar', 'Escalar'), ('cerrar', 'Cerrar'), ('aprobar', 'Aprobar'), ('rechazar', 'Rechazar'), ('exportar', 'Exportar'), ('buscar', 'Buscar'), ('filtrar', 'Filtrar'), ('error', 'Error')], max_length=50, verbose_name='Acción')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Detalles Adicionales')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='audit_audit_timesta_19e18a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='audit_audit_user_id_e8be02_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'timestamp'], name='audit_audit_action_2a1328_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip_address', 'timestamp'], name='audit_audit_ip_addr_4a1174_idx'),
        ),
    ]
