# Generated by Django 4.2.7 on 2025-10-03 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('rule_type', models.CharField(choices=[('include', 'Incluir'), ('exclude', 'Excluir'), ('alert', 'Alerta'), ('block', 'Bloquear')], max_length=20, verbose_name='Tipo de Regla')),
                ('action_filter', models.CharField(blank=True, max_length=50, verbose_name='Filtro de Acción')),
                ('user_filter', models.CharField(blank=True, max_length=100, verbose_name='Filtro de Usuario')),
                ('ip_filter', models.CharField(blank=True, max_length=100, verbose_name='Filtro de IP')),
                ('module_filter', models.CharField(blank=True, max_length=100, verbose_name='Filtro de Módulo')),
                ('severity_filter', models.CharField(blank=True, max_length=20, verbose_name='Filtro de Severidad')),
                ('category_filter', models.CharField(blank=True, max_length=50, verbose_name='Filtro de Categoría')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Prioridad')),
                ('alert_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de Alerta')),
                ('alert_webhook', models.URLField(blank=True, verbose_name='Webhook de Alerta')),
                ('block_action', models.BooleanField(default=False, verbose_name='Bloquear Acción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_audit_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Regla de Auditoría',
                'verbose_name_plural': 'Reglas de Auditoría',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('report_type', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('yearly', 'Anual'), ('custom', 'Personalizado')], max_length=20, verbose_name='Tipo de Reporte')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('generating', 'Generando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('date_from', models.DateTimeField(verbose_name='Fecha Desde')),
                ('date_to', models.DateTimeField(verbose_name='Fecha Hasta')),
                ('user_filter', models.CharField(blank=True, max_length=100, verbose_name='Filtro de Usuario')),
                ('action_filter', models.CharField(blank=True, max_length=50, verbose_name='Filtro de Acción')),
                ('severity_filter', models.CharField(blank=True, max_length=20, verbose_name='Filtro de Severidad')),
                ('category_filter', models.CharField(blank=True, max_length=50, verbose_name='Filtro de Categoría')),
                ('include_details', models.BooleanField(default=True, verbose_name='Incluir Detalles')),
                ('include_changes', models.BooleanField(default=True, verbose_name='Incluir Cambios')),
                ('include_metadata', models.BooleanField(default=False, verbose_name='Incluir Metadatos')),
                ('group_by', models.CharField(blank=True, max_length=50, verbose_name='Agrupar Por')),
                ('total_records', models.PositiveIntegerField(default=0, verbose_name='Total de Registros')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Ruta del Archivo')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Tamaño del Archivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_audit_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Auditoría',
                'verbose_name_plural': 'Reportes de Auditoría',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Crear'), ('update', 'Actualizar'), ('delete', 'Eliminar'), ('view', 'Ver'), ('login', 'Iniciar Sesión'), ('logout', 'Cerrar Sesión'), ('approve', 'Aprobar'), ('reject', 'Rechazar'), ('escalate', 'Escalar'), ('assign', 'Asignar'), ('upload', 'Subir'), ('download', 'Descargar'), ('export', 'Exportar'), ('import', 'Importar'), ('search', 'Buscar'), ('filter', 'Filtrar'), ('sort', 'Ordenar'), ('print', 'Imprimir'), ('share', 'Compartir'), ('comment', 'Comentar'), ('tag', 'Etiquetar'), ('archive', 'Archivar'), ('restore', 'Restaurar'), ('backup', 'Respaldo'), ('restore_backup', 'Restaurar Respaldo'), ('system_action', 'Acción del Sistema'), ('error', 'Error'), ('warning', 'Advertencia'), ('info', 'Información'), ('debug', 'Debug')], max_length=50, verbose_name='Acción')),
                ('result', models.CharField(choices=[('success', 'Éxito'), ('failure', 'Fallo'), ('partial', 'Parcial'), ('cancelled', 'Cancelado'), ('timeout', 'Tiempo Agotado'), ('unauthorized', 'No Autorizado'), ('forbidden', 'Prohibido'), ('not_found', 'No Encontrado'), ('error', 'Error')], default='success', max_length=20, verbose_name='Resultado')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Clave de Sesión')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('old_values', models.JSONField(blank=True, default=dict, verbose_name='Valores Anteriores')),
                ('new_values', models.JSONField(blank=True, default=dict, verbose_name='Valores Nuevos')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duración')),
                ('module', models.CharField(blank=True, max_length=100, verbose_name='Módulo')),
                ('function', models.CharField(blank=True, max_length=100, verbose_name='Función')),
                ('line_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Línea')),
                ('severity', models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto'), ('critical', 'Crítico')], default='medium', max_length=20, verbose_name='Severidad')),
                ('category', models.CharField(choices=[('authentication', 'Autenticación'), ('authorization', 'Autorización'), ('data_access', 'Acceso a Datos'), ('data_modification', 'Modificación de Datos'), ('system_config', 'Configuración del Sistema'), ('user_management', 'Gestión de Usuarios'), ('security', 'Seguridad'), ('performance', 'Rendimiento'), ('error', 'Error'), ('business_logic', 'Lógica de Negocio'), ('integration', 'Integración'), ('backup', 'Respaldo'), ('audit', 'Auditoría')], default='data_access', max_length=50, verbose_name='Categoría')),
                ('request_id', models.CharField(blank=True, max_length=100, verbose_name='ID de Request')),
                ('correlation_id', models.CharField(blank=True, max_length=100, verbose_name='ID de Correlación')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('widgets_config', models.JSONField(default=dict, verbose_name='Configuración de Widgets')),
                ('default_filters', models.JSONField(default=dict, verbose_name='Filtros por Defecto')),
                ('auto_refresh', models.BooleanField(default=True, verbose_name='Actualización Automática')),
                ('refresh_interval', models.PositiveIntegerField(default=300, verbose_name='Intervalo de Actualización (segundos)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_audit_dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard de Auditoría',
                'verbose_name_plural': 'Dashboards de Auditoría',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('severity', models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto'), ('critical', 'Crítico')], max_length=20, verbose_name='Severidad')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('acknowledged', 'Reconocido'), ('resolved', 'Resuelto'), ('dismissed', 'Descartado')], default='active', max_length=20, verbose_name='Estado')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notas de Resolución')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='audit.auditlog')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_audit_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta de Auditoría',
                'verbose_name_plural': 'Alertas de Auditoría',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='audit_audit_timesta_19e18a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='audit_audit_user_id_e8be02_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'timestamp'], name='audit_audit_action_2a1328_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['result', 'timestamp'], name='audit_audit_result_94d7ba_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['severity', 'timestamp'], name='audit_audit_severit_4d72db_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['category', 'timestamp'], name='audit_audit_categor_c661fd_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_4c2ead_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip_address', 'timestamp'], name='audit_audit_ip_addr_4a1174_idx'),
        ),
    ]
