# Generated by Django 4.2.7 on 2025-12-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [

        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Iniciar Sesión'), ('logout', 'Cerrar Sesión'), ('crear', 'Crear'), ('actualizar', 'Actualizar'), ('eliminar', 'Eliminar'), ('ver', 'Ver'), ('subir', 'Subir Archivo'), ('descargar', 'Descargar Archivo'), ('escalar', 'Escalar'), ('cerrar', 'Cerrar'), ('aprobar', 'Aprobar'), ('rechazar', 'Rechazar'), ('exportar', 'Exportar'), ('buscar', 'Buscar'), ('filtrar', 'Filtrar'), ('error', 'Error')], db_index=True, max_length=50, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='Dirección IP'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y Hora'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp', 'action'], name='audit_audit_timesta_0aa31e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'action'], name='audit_audit_user_id_ac289d_idx'),
        ),
    ]
