# Generated by Django 4.2.7 on 2025-12-10 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_remove_auditlog_audit_audit_timesta_19e18a_idx_and_more'),
    ]

    operations = [

    ]
