# Generated by Django 4.2.7 on 2026-01-08 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_remove_auditlog_audit_audit_timesta_19e18a_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_audit_timesta_19e18a_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_audit_user_id_e8be02_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_audit_action_2a1328_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_audit_ip_addr_4a1174_idx',
        ),
    ]
