# Generated by Django 4.2.7 on 2026-01-27 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0005_remove_auditlog_audit_audit_timesta_19e18a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.CharField(help_text='ID original del objeto', max_length=255)),
                ('model_name', models.CharField(help_text='Nombre del modelo (ej. Incident)', max_length=100)),
                ('app_label', models.CharField(help_text='App del modelo (ej. incidents)', max_length=100)),
                ('serialized_data', models.JSONField(help_text='Datos completos del objeto en formato JSON')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('restore_deadline', models.DateTimeField(db_index=True)),
                ('deletion_reason', models.TextField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Elemento Eliminado',
                'verbose_name_plural': 'Elementos Eliminados (Papelera)',
                'ordering': ['-deleted_at'],
                'indexes': [models.Index(fields=['app_label', 'model_name'], name='audit_delet_app_lab_ecbc63_idx'), models.Index(fields=['deleted_at'], name='audit_delet_deleted_f30baa_idx')],
            },
        ),
    ]
