# Generated by Django 4.2.7 on 2026-01-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_deleteditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleteditem',
            name='object_repr',
            field=models.CharField(default='Elemento eliminado', help_text='Representación legible del objeto', max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_login', 'Iniciar Sesión'), ('user_logout', 'Cerrar Sesión'), ('incident_created', 'Incidente Creado'), ('incident_closed', 'Incidente Cerrado'), ('escalation_triggered', 'Incidente Escalado'), ('report_attached', 'Reporte Adjuntado'), ('create', 'Crear'), ('delete', 'Eliminar'), ('item_restored', 'Elemento Restaurado')], db_index=True, max_length=50, verbose_name='Acción'),
        ),
    ]
