# Generated by Django 4.2.7 on 2026-03-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_deleteditem_object_repr_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_login', 'Iniciar Sesión'), ('user_logout', 'Cerrar Sesión'), ('incident_created', 'Incidente Creado'), ('incident_closed', 'Incidente Cerrado'), ('escalation_triggered', 'Incidente Escalado'), ('report_attached', 'Reporte Adjuntado'), ('report_created', 'Reporte Creado'), ('report_updated', 'Reporte Editado'), ('create', 'Crear'), ('update', 'Actualizar'), ('delete', 'Eliminar'), ('item_restored', 'Elemento Restaurado'), ('sap_sync_error', 'Fallo Sincronización SAP'), ('pdf_error', 'Error en Generación de PDF'), ('api_error', 'Error de Integración API')], db_index=True, max_length=50, verbose_name='Acción'),
        ),
    ]
