# Generated by Django 4.2.7 on 2025-09-10 14:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código único de la incidencia (ej. INC-2025-0001)', max_length=20, unique=True)),
                ('provider', models.CharField(help_text='Proveedor del producto', max_length=200)),
                ('obra', models.CharField(help_text='Obra o proyecto', max_length=200)),
                ('cliente', models.CharField(help_text='Nombre del cliente', max_length=200)),
                ('cliente_rut', models.CharField(blank=True, help_text='RUT del cliente', max_length=20)),
                ('direccion_cliente', models.TextField(blank=True, help_text='Dirección del cliente')),
                ('sku', models.CharField(help_text='SKU del producto', max_length=100)),
                ('lote', models.CharField(blank=True, help_text='Número de lote', max_length=100)),
                ('factura_num', models.CharField(blank=True, help_text='Número de factura', max_length=100)),
                ('pedido_num', models.CharField(blank=True, help_text='Número de pedido', max_length=100)),
                ('fecha_reporte', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora del reporte')),
                ('fecha_deteccion', models.DateField(help_text='Fecha de detección del problema')),
                ('hora_deteccion', models.TimeField(help_text='Hora de detección del problema')),
                ('descripcion', models.TextField(help_text='Descripción detallada del problema')),
                ('acciones_inmediatas', models.TextField(blank=True, help_text='Acciones inmediatas adoptadas')),
                ('categoria', models.CharField(choices=[('tuberia', 'Tubería'), ('accesorio_plastico', 'Accesorio Plástico'), ('accesorio_metalico', 'Accesorio Metálico'), ('llave', 'Llave'), ('otro', 'Otro')], help_text='Categoría del producto', max_length=50)),
                ('subcategoria', models.CharField(blank=True, help_text='Subcategoría específica', max_length=100)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', help_text='Prioridad de la incidencia', max_length=20)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('triage', 'Triage'), ('inspeccion', 'Inspección'), ('laboratorio', 'Laboratorio'), ('propuesta', 'Propuesta'), ('en_progreso', 'En Progreso'), ('cerrado', 'Cerrado')], default='abierto', help_text='Estado actual de la incidencia', max_length=20)),
                ('lab_required', models.BooleanField(default=False, help_text='Indica si se requiere análisis de laboratorio')),
                ('acciones_posteriores', models.TextField(blank=True, help_text='Registro de evolución/acciones posteriores')),
                ('nc_number', models.CharField(blank=True, help_text='Número de nota de crédito', max_length=100)),
                ('np_number', models.CharField(blank=True, help_text='Número de nota de pedido', max_length=100)),
                ('ai_analysis', models.JSONField(blank=True, help_text='Análisis realizado por IA', null=True)),
                ('ai_analysis_accuracy', models.FloatField(blank=True, help_text='Precisión del análisis de IA (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('fecha_cierre', models.DateField(blank=True, help_text='Fecha de cierre de la incidencia', null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='Fecha y hora de cierre', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Usuario asignado para resolver la incidencia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, help_text='Usuario que cerró la incidencia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_incidents', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='Usuario que creó la incidencia', on_delete=django.db.models.deletion.PROTECT, related_name='created_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'db_table': 'incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_description', models.TextField(help_text='Descripción de la muestra enviada')),
                ('tests_performed', models.JSONField(default=list, help_text='Lista de ensayos realizados')),
                ('observations', models.TextField(help_text='Observaciones del laboratorio')),
                ('conclusions', models.TextField(help_text='Conclusiones técnicas del laboratorio')),
                ('expert_name', models.CharField(help_text='Nombre del experto que realizó el análisis', max_length=200)),
                ('expert_signature_path', models.CharField(blank=True, help_text='Ruta de la firma del experto', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='Usuario que creó el reporte', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(help_text='Incidencia relacionada', on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to='incidents.incident')),
            ],
            options={
                'verbose_name': 'Reporte de Laboratorio',
                'verbose_name_plural': 'Reportes de Laboratorio',
                'db_table': 'lab_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Creado'), ('updated', 'Actualizado'), ('assigned', 'Asignado'), ('status_changed', 'Estado Cambiado'), ('image_uploaded', 'Imagen Subida'), ('document_generated', 'Documento Generado'), ('lab_report_added', 'Reporte de Lab Agregado'), ('closed', 'Cerrado'), ('reopened', 'Reabierto')], help_text='Acción realizada', max_length=50)),
                ('description', models.TextField(help_text='Descripción de la acción')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadatos adicionales de la acción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(help_text='Incidencia relacionada', on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='incidents.incident')),
                ('user', models.ForeignKey(help_text='Usuario que realizó la acción', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Línea de Tiempo',
                'verbose_name_plural': 'Líneas de Tiempo',
                'db_table': 'incident_timeline',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Nombre del archivo', max_length=255)),
                ('path', models.CharField(help_text='Ruta del archivo en el storage', max_length=500)),
                ('file_size', models.BigIntegerField(help_text='Tamaño del archivo en bytes')),
                ('mime_type', models.CharField(help_text='Tipo MIME del archivo', max_length=100)),
                ('exif_json', models.JSONField(blank=True, default=dict, help_text='Datos EXIF de la imagen')),
                ('caption_ai', models.TextField(blank=True, help_text='Descripción generada por IA')),
                ('analysis_json', models.JSONField(blank=True, default=dict, help_text='Análisis completo de IA (causas sugeridas, confianza, etc.)')),
                ('ai_provider_used', models.CharField(blank=True, help_text='Proveedor de IA utilizado para el análisis', max_length=50)),
                ('ai_confidence', models.FloatField(blank=True, help_text='Nivel de confianza del análisis de IA (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(help_text='Incidencia relacionada', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='incidents.incident')),
                ('uploaded_by', models.ForeignKey(help_text='Usuario que subió la imagen', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imagen de Incidencia',
                'verbose_name_plural': 'Imágenes de Incidencias',
                'db_table': 'incident_images',
                'ordering': ['-created_at'],
            },
        ),
    ]
