# Generated by Django 4.2.7 on 2025-09-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_alter_incident_created_by_and_more'),
    ]

    operations = [
    ]
