# Generated by Django 4.2.7 on 2025-10-03 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0009_optimize_incidents_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='responsable',
            field=models.CharField(choices=[('patricio_morales', 'Patricio Morales'), ('marco_montenegro', 'Marco Montenegro')], help_text='Responsable técnico asignado', max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='sku',
            field=models.CharField(default='N/A', help_text='SKU del producto', max_length=100),
        ),
        migrations.AlterField(
            model_name='incidentattachment',
            name='file_type',
            field=models.CharField(choices=[('image', 'Imagen'), ('document', 'Documento'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Otro')], help_text='Tipo de archivo', max_length=50),
        ),
        migrations.AlterField(
            model_name='incidentattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que subió el archivo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidenttimeline',
            name='action',
            field=models.CharField(choices=[('created', 'Creado'), ('updated', 'Actualizado'), ('assigned', 'Asignado'), ('status_changed', 'Estado Cambiado'), ('image_uploaded', 'Imagen Subida'), ('document_generated', 'Documento Generado'), ('lab_report_added', 'Reporte de Lab Agregado'), ('closed', 'Cerrado'), ('reopened', 'Reabierto'), ('deleted', 'Eliminado')], help_text='Acción realizada', max_length=50),
        ),
    ]
