# Generated by Django 4.2.7 on 2025-10-06 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0010_alter_incident_responsable_alter_incident_sku_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Responsables',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='incident',
            name='prioridad',
            field=models.CharField(default='media', help_text='Prioridad de la incidencia', max_length=20),
        ),
        # Drop index that may depend on the categoria column before migrating it (SQL Server locks depending objects)
        migrations.RunSQL(
            """
            IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'idx_incidents_categoria' AND object_id = OBJECT_ID('incidents'))
                DROP INDEX idx_incidents_categoria ON incidents;
            """,
            reverse_sql="""
            IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'idx_incidents_categoria')
                CREATE INDEX idx_incidents_categoria ON incidents(categoria);
            """,
        ),
        # Safely migrate text categories into Category rows and populate a new categoria_id BIGINT column
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Add a new nullable bigint column to hold FK values
                migrations.RunSQL(
                    "ALTER TABLE incidents ADD categoria_id BIGINT NULL;",
                    reverse_sql="ALTER TABLE incidents DROP COLUMN categoria_id;",
                ),
                # Create Category rows from distinct existing text values
                migrations.RunSQL(
                    """
                    INSERT INTO incidents_category (name, description)
                    SELECT DISTINCT categoria, '' FROM incidents WHERE categoria IS NOT NULL AND categoria <> '';
                    """,
                    reverse_sql="DELETE FROM incidents_category WHERE name IN (SELECT DISTINCT categoria FROM incidents WHERE categoria IS NOT NULL AND categoria <> '');",
                ),
                # Populate the new categoria_id column by joining on the newly created categories
                migrations.RunSQL(
                    """
                    UPDATE incidents
                    SET categoria_id = c.id
                    FROM incidents_category c
                    WHERE incidents.categoria = c.name;
                    """,
                    reverse_sql="UPDATE incidents SET categoria_id = NULL;",
                ),
                # Drop the old text column now that values have been migrated
                migrations.RunSQL(
                    "ALTER TABLE incidents DROP COLUMN categoria;",
                    reverse_sql="ALTER TABLE incidents ADD categoria NVARCHAR(50) NULL;",
                ),
                # Add FK constraint from categoria_id to incidents_category(id)
                migrations.RunSQL(
                    "ALTER TABLE incidents ADD CONSTRAINT FK_incidents_categoria FOREIGN KEY (categoria_id) REFERENCES incidents_category(id);",
                    reverse_sql="ALTER TABLE incidents DROP CONSTRAINT IF EXISTS FK_incidents_categoria;",
                ),
            ],
            state_operations=[
                # Update Django state so the 'categoria' field becomes a ForeignKey to Category
                migrations.AlterField(
                    model_name='incident',
                    name='categoria',
                    field=models.ForeignKey(help_text='Categoría del producto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.category'),
                ),
            ],
        ),
        # Replace textual 'responsable' with FK to Responsible safely (avoid ALTER COLUMN while indexes exist)
        migrations.RunSQL(
            """
            IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'idx_incidents_responsable' AND object_id = OBJECT_ID('incidents'))
                DROP INDEX idx_incidents_responsable ON incidents;
            """,
            reverse_sql="""
            IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'idx_incidents_responsable')
                CREATE INDEX idx_incidents_responsable ON incidents(responsable);
            """,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE incidents ADD responsable_id BIGINT NULL;",
                    reverse_sql="ALTER TABLE incidents DROP COLUMN responsable_id;",
                ),
                migrations.RunSQL(
                    """
                    INSERT INTO incidents_responsible (name, email, active)
                    SELECT DISTINCT responsable, '', 1 FROM incidents WHERE responsable IS NOT NULL AND responsable <> '';
                    """,
                    reverse_sql="DELETE FROM incidents_responsible WHERE name IN (SELECT DISTINCT responsable FROM incidents WHERE responsable IS NOT NULL AND responsable <> '');",
                ),
                migrations.RunSQL(
                    """
                    UPDATE incidents
                    SET responsable_id = r.id
                    FROM incidents_responsible r
                    WHERE incidents.responsable = r.name;
                    """,
                    reverse_sql="UPDATE incidents SET responsable_id = NULL;",
                ),
                migrations.RunSQL(
                    "ALTER TABLE incidents DROP COLUMN responsable;",
                    reverse_sql="ALTER TABLE incidents ADD responsable NVARCHAR(100) NULL;",
                ),
                migrations.RunSQL(
                    "ALTER TABLE incidents ADD CONSTRAINT FK_incidents_responsable FOREIGN KEY (responsable_id) REFERENCES incidents_responsible(id);",
                    reverse_sql="ALTER TABLE incidents DROP CONSTRAINT IF EXISTS FK_incidents_responsable;",
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='incident',
                    name='responsable',
                    field=models.ForeignKey(help_text='Responsable técnico asignado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.responsible'),
                ),
            ],
        ),
        # Recreate the index on the new FK column (categoria_id)
        migrations.RunSQL(
            """
            IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'idx_incidents_categoria')
                CREATE INDEX idx_incidents_categoria ON incidents(categoria_id);
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_incidents_categoria;",
        ),
    ]
