# Generated by Django 4.2.7 on 2025-12-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0011_category_responsible_alter_incident_prioridad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='closed_at_stage',
            field=models.CharField(blank=True, choices=[('incidencia', 'Cerrada en Incidencia'), ('reporte_visita', 'Cerrada en Reporte de Visita'), ('calidad', 'Cerrada en Calidad'), ('proveedor', 'Cerrada en Proveedor')], help_text='Etapa del workflow en la que se cerró la incidencia', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('reporte_visita', 'En Reporte de Visita'), ('calidad', 'En Calidad'), ('proveedor', 'En Proveedor'), ('cerrado', 'Cerrado')], default='abierto', help_text='Estado actual de la incidencia', max_length=20),
        ),
    ]
