# Generated by Django 4.2.7 on 2025-12-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0012_add_workflow_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='closure_attachment',
            field=models.CharField(blank=True, help_text='Ruta del archivo adjunto con información de cierre', max_length=500),
        ),
        migrations.AddField(
            model_name='incident',
            name='closure_summary',
            field=models.TextField(blank=True, help_text='Resumen obligatorio de acciones, conclusiones y decisiones tomadas al cerrar la incidencia'),
        ),
        migrations.AddField(
            model_name='incident',
            name='first_response_at',
            field=models.DateTimeField(blank=True, help_text='Fecha/hora de primera respuesta', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolution_time_hours',
            field=models.FloatField(blank=True, help_text='Tiempo total de resolución en horas', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='sla_breached',
            field=models.BooleanField(default=False, help_text='Indica si se incumplió el SLA'),
        ),
        migrations.AddField(
            model_name='incident',
            name='sla_due_date',
            field=models.DateTimeField(blank=True, help_text='Fecha límite según SLA', null=True),
        ),
    ]
