# Generated by Django 4.2.7 on 2025-12-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0013_add_closure_and_sla_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['estado', 'prioridad'], name='incidents_estado_dca940_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['created_at', 'estado'], name='incidents_created_9577d0_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['cliente_rut'], name='incidents_cliente_6e528e_idx'),
        ),
    ]
