# Generated by Django 4.2.7 on 2026-01-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0014_alter_incident_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='escalated_to_internal_quality',
            field=models.BooleanField(default=False, help_text='Indica si la incidencia fue escalada a calidad interna'),
        ),
    ]
