# Generated by Django 4.2.7 on 2026-01-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0015_incident_escalated_to_internal_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='customer_code',
            field=models.CharField(blank=True, help_text='Código del cliente en SAP (CardCode)', max_length=50),
        ),
        migrations.AddField(
            model_name='incident',
            name='project_code',
            field=models.CharField(blank=True, help_text='Código del proyecto en SAP (BPProjCode)', max_length=50),
        ),
        migrations.AddField(
            model_name='incident',
            name='salesperson',
            field=models.CharField(blank=True, help_text='Vendedor asignado (U_NX_VENDEDOR)', max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='sap_call_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID de Llamada de Servicio en SAP', null=True),
        ),
    ]
