# Generated by Django 4.2.7 on 2026-02-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0016_incident_customer_code_incident_project_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='acciones_inmediatas',
            field=models.TextField(blank=True, default='', help_text='Acciones inmediatas adoptadas', null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='cliente_rut',
            field=models.CharField(blank=True, default='', help_text='RUT del cliente', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='customer_code',
            field=models.CharField(blank=True, default='', help_text='Código del cliente en SAP (CardCode)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='factura_num',
            field=models.CharField(blank=True, default='', help_text='Número de factura', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='lote',
            field=models.CharField(blank=True, default='', help_text='Número de lote', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='nc_number',
            field=models.CharField(blank=True, default='', help_text='Número de nota de crédito', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='np_number',
            field=models.CharField(blank=True, default='', help_text='Número de nota de pedido', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='obra',
            field=models.CharField(blank=True, help_text='Obra o proyecto', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='pedido_num',
            field=models.CharField(blank=True, default='', help_text='Número de pedido', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='project_code',
            field=models.CharField(blank=True, default='', help_text='Código del proyecto en SAP (BPProjCode)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='provider',
            field=models.CharField(blank=True, help_text='Proveedor del producto', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='salesperson',
            field=models.CharField(blank=True, default='', help_text='Vendedor asignado (U_NX_VENDEDOR)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='subcategoria',
            field=models.CharField(blank=True, default='', help_text='Subcategoría específica', max_length=100, null=True),
        ),
    ]
