# Generated by Django 4.2.7 on 2026-02-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0017_alter_incident_acciones_inmediatas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='acciones_posteriores',
            field=models.TextField(blank=True, help_text='Registro de evolución/acciones posteriores', null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='direccion_cliente',
            field=models.TextField(blank=True, help_text='Dirección del cliente', null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='escalation_reason',
            field=models.TextField(blank=True, help_text='Razón del escalamiento', null=True),
        ),
    ]
