# Generated by Django 4.2.7 on 2026-02-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0018_alter_incident_acciones_posteriores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sap_problem_type_id',
            field=models.IntegerField(blank=True, help_text='ID del Tipo de Problema en SAP (OSCL.problemType)', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='salesperson_code',
            field=models.IntegerField(blank=True, help_text='Código del vendedor en SAP (SlpCode)', null=True),
        ),
        migrations.AddField(
            model_name='responsible',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='responsible',
            name='sap_technician_id',
            field=models.IntegerField(blank=True, help_text='ID del técnico en SAP (OHEM.empID)', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='incident',
            name='salesperson',
            field=models.CharField(blank=True, default='', help_text='Vendedor asignado (Nombre)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
