# Generated by Django 4.2.7 on 2026-02-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0019_category_sap_problem_type_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='sap_doc_num',
            field=models.IntegerField(blank=True, db_index=True, help_text='DocNum oficial de Llamada de Servicio en SAP', null=True),
        ),
    ]
