# Generated by Django 4.2.7 on 2026-03-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0020_incident_sap_doc_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ciudad del cliente u obra', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='comuna',
            field=models.CharField(blank=True, help_text='Comuna del cliente u obra', max_length=100, null=True),
        ),
    ]
