# Generated by Django 4.2.7 on 2026-03-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0021_incident_ciudad_incident_comuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='cliente',
            field=models.CharField(db_index=True, help_text='Nombre del cliente', max_length=200),
        ),
        migrations.AlterField(
            model_name='incident',
            name='obra',
            field=models.CharField(blank=True, db_index=True, help_text='Obra o proyecto', max_length=200, null=True),
        ),
    ]
