# Generated by Django 4.2.7 on 2026-03-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0023_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='technician_code',
            field=models.IntegerField(blank=True, help_text='Código del técnico responsable en SAP (EmpID)', null=True),
        ),
    ]
