# Generated by Django 4.2.7 on 2026-03-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0024_incident_technician_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('reporte_visita', 'En Reporte de Visita'), ('calidad', 'En Calidad'), ('proveedor', 'En Proveedor'), ('cerrado', 'Cerrado'), ('cancelada', 'Cancelada')], default='abierto', help_text='Estado actual de la incidencia', max_length=20),
        ),
        migrations.AlterField(
            model_name='incidenttimeline',
            name='action',
            field=models.CharField(choices=[('created', 'Creado'), ('updated', 'Actualizado'), ('assigned', 'Asignado'), ('status_changed', 'Estado Cambiado'), ('cancelled', 'Cancelada'), ('image_uploaded', 'Imagen Subida'), ('document_generated', 'Documento Generado'), ('lab_report_added', 'Reporte de Lab Agregado'), ('closed', 'Cerrado'), ('reopened', 'Reabierto'), ('deleted', 'Eliminado')], help_text='Acción realizada', max_length=50),
        ),
    ]
