# Generated by Django 4.2.7 on 2026-04-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0025_alter_incident_estado_alter_incidenttimeline_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='cliente_rut',
            field=models.CharField(blank=True, db_index=True, default='', help_text='RUT del cliente', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='lote',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Número de lote', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='subcategoria',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Subcategoría específica', max_length=100, null=True),
        ),
    ]
