# Generated by Django 4.2.7 on 2026-04-08 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0026_alter_incident_cliente_rut_alter_incident_lote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='sku',
        ),
    ]
