# Generated by Django 4.2.7 on 2026-04-24 12:51

import apps.visits.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(max_length=50, unique=True, verbose_name='Número de Reporte')),
                ('order_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de Orden')),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Visita')),
                ('project_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Proyecto')),
                ('project_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID del Proyecto')),
                ('client_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Cliente')),
                ('client_rut', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Cliente')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('construction_company', models.CharField(blank=True, max_length=200, verbose_name='Empresa Constructora')),
                ('salesperson', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendedor')),
                ('technician', models.CharField(blank=True, max_length=100, null=True, verbose_name='Técnico')),
                ('technician_id', models.IntegerField(blank=True, null=True, verbose_name='ID Técnico SAP')),
                ('installer', models.CharField(blank=True, max_length=100, verbose_name='Instalador')),
                ('installer_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del Instalador')),
                ('professional_name', models.CharField(blank=True, max_length=100, verbose_name='Profesional de Obra')),
                ('technical_inspector', models.CharField(blank=True, max_length=100, verbose_name='Inspector Técnico de Obra')),
                ('quality_manager', models.CharField(blank=True, max_length=100, verbose_name='Encargado de Calidad')),
                ('management_manager', models.CharField(blank=True, max_length=100, verbose_name='Encargado de Gestión')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='Fax')),
                ('contact_observations', models.TextField(blank=True, verbose_name='Observaciones de Contacto')),
                ('commune', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comuna')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('visit_reason', models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo de la Visita')),
                ('machine_data', models.JSONField(blank=True, default=dict, verbose_name='Datos de Máquinas')),
                ('materials_data', models.JSONField(blank=True, default=list, verbose_name='Tabla de Materiales')),
                ('wall_observations', models.TextField(blank=True, verbose_name='Observaciones Muro/Tabique')),
                ('matrix_observations', models.TextField(blank=True, verbose_name='Observaciones Matriz')),
                ('slab_observations', models.TextField(blank=True, verbose_name='Observaciones Losa')),
                ('storage_observations', models.TextField(blank=True, verbose_name='Observaciones Almacenaje')),
                ('pre_assembled_observations', models.TextField(blank=True, verbose_name='Observaciones Pre Armados')),
                ('exterior_observations', models.TextField(blank=True, verbose_name='Observaciones Exteriores')),
                ('general_observations', models.TextField(blank=True, verbose_name='Observaciones Generales')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending_review', 'Pendiente de Revisión'), ('approved', 'Aprobado'), ('sent', 'Enviado'), ('waiting_response', 'Esperando Respuesta'), ('closed', 'Cerrado')], db_index=True, default='draft', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=apps.visits.models.get_visit_report_pdf_path, verbose_name='PDF del Reporte')),
                ('technician_signature', models.BooleanField(default=False, verbose_name='Firma del Técnico')),
                ('installer_signature', models.BooleanField(default=False, verbose_name='Firma del Instalador')),
                ('docx_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ruta del documento DOCX')),
                ('pdf_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ruta del documento PDF')),
                ('sap_call_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID Llamada SAP')),
                ('sap_doc_num', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='DocNum Oficial SAP')),
                ('sync_status', models.CharField(default='pending', max_length=20, verbose_name='Estado Sincronización')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronización')),
                ('sync_error_message', models.TextField(blank=True, null=True, verbose_name='Error Sincronización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visit_reports', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Reporte de Visita',
                'verbose_name_plural': 'Reportes de Visita',
                'ordering': ['-created_at'],
            },
        ),
    ]
