# Generated by Django 4.2.7 on 2026-04-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitreport',
            name='client_signature',
            field=models.TextField(blank=True, null=True, verbose_name='Firma del Cliente (Base64)'),
        ),
    ]
