# Generated by Django 4.2.7 on 2026-04-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_visitreport_client_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitreport',
            name='incident_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Código Incidencia'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='incident_description',
            field=models.TextField(blank=True, verbose_name='Descripción Incidencia'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='incident_detection_date',
            field=models.CharField(blank=True, max_length=20, verbose_name='Fecha Detección'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='incident_detection_time',
            field=models.CharField(blank=True, max_length=20, verbose_name='Hora Detección'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='incident_immediate_actions',
            field=models.TextField(blank=True, verbose_name='Acciones Inmediatas'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='incident_priority',
            field=models.CharField(blank=True, max_length=50, verbose_name='Prioridad Incidencia'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='incident_responsible',
            field=models.CharField(blank=True, max_length=100, verbose_name='Responsable Incidencia'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='product_category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Categoría Producto'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='product_provider',
            field=models.CharField(blank=True, max_length=100, verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='product_subcategory',
            field=models.CharField(blank=True, max_length=100, verbose_name='Subcategoría Producto'),
        ),
    ]
