# Generated by Django 4.2.7 on 2026-04-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_fix_signature_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitreport',
            name='installation_level',
            field=models.CharField(default='NORMAL', max_length=50, verbose_name='Nivel de Instalación'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='is_mixed_material',
            field=models.BooleanField(default=False, verbose_name='Material Mixto'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='is_other_provider',
            field=models.BooleanField(default=False, verbose_name='Obra con otro proveedor'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='is_project_finished',
            field=models.BooleanField(default=False, verbose_name='Obra Terminada'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='is_rescued_project',
            field=models.BooleanField(default=False, verbose_name='Obra Rescatada'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='other_provider_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre del otro proveedor'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='patent_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número de Patente'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='visit_reason',
            field=models.CharField(blank=True, default='1', max_length=100, null=True, verbose_name='Motivo de la Visita'),
        ),
    ]
