# Generated by Django 4.2.7 on 2026-04-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0005_visitreport_installation_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitreport',
            name='installation_level',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('DEFICIENTE', 'Deficiente'), ('CRITICO', 'Crítico'), ('INEXISTENTE', 'Inexistente'), ('NO_APLICA', 'No Aplica')], default='NORMAL', max_length=50, verbose_name='Nivel de Instalación'),
        ),
    ]
