# Generated by Django 4.2.7 on 2026-05-05 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0006_alter_visitreport_installation_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitreport',
            name='management_manager',
        ),
        migrations.RemoveField(
            model_name='visitreport',
            name='quality_manager',
        ),
        migrations.RemoveField(
            model_name='visitreport',
            name='technical_inspector',
        ),
    ]
