# Generated by Django 4.2.7 on 2026-05-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0007_remove_visitreport_management_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitreport',
            name='critical_observations',
            field=models.TextField(blank=True, verbose_name='Observación Crítica (Interna)'),
        ),
    ]
