# Generated by Django 4.2.7 on 2026-05-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0008_add_critical_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitreport',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teléfono Llamada SAP'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='installation_level',
            field=models.CharField(choices=[('0', 'Normal'), ('1', 'Deficiente'), ('2', 'Crítico'), ('3', 'Inexistente'), ('4', 'No Aplica')], default='0', max_length=50, verbose_name='Nivel de Instalación'),
        ),
    ]
