# Generated by Django 4.2.7 on 2026-05-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0009_visitreport_telephone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitreport',
            options={'verbose_name': 'Reporte de Visita', 'verbose_name_plural': 'Reportes de Visita'},
        ),
        migrations.AddField(
            model_name='visitreport',
            name='client_contact',
            field=models.CharField(blank=True, max_length=200, verbose_name='Persona de Contacto'),
        ),
    ]
