# Generated by Django 4.2.7 on 2026-05-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0010_alter_visitreport_options_visitreport_client_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitreport',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del Cliente'),
        ),
    ]
