# Generated by Django 4.2.7 on 2026-05-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0011_visitreport_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitreport',
            name='client_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email del Cliente'),
        ),
    ]
