# Generated by Django 4.2.7 on 2025-10-03 13:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google Gemini'), ('local', 'Modelo Local')], help_text='Nombre del proveedor de IA', max_length=50, unique=True)),
                ('api_key_encrypted', models.TextField(blank=True, help_text='API Key encriptada')),
                ('enabled', models.BooleanField(default=True, help_text='Indica si el proveedor está habilitado')),
                ('priority', models.IntegerField(default=1, help_text='Prioridad del proveedor (menor número = mayor prioridad)')),
                ('daily_quota_tokens', models.IntegerField(default=100000, help_text='Cuota diaria de tokens')),
                ('daily_quota_calls', models.IntegerField(default=1000, help_text='Cuota diaria de llamadas')),
                ('quota_reset_time', models.TimeField(default='00:00', help_text='Hora de reinicio de cuota (formato HH:MM)')),
                ('tokens_used_today', models.IntegerField(default=0, help_text='Tokens utilizados hoy')),
                ('calls_made_today', models.IntegerField(default=0, help_text='Llamadas realizadas hoy')),
                ('last_reset_date', models.DateField(default=django.utils.timezone.now, help_text='Última fecha de reinicio de cuota')),
                ('allow_external_uploads', models.BooleanField(default=True, help_text='Permitir envío de datos a proveedores externos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor de IA',
                'verbose_name_plural': 'Proveedores de IA',
                'db_table': 'ai_providers',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('image_caption', 'Descripción de Imagen'), ('image_analysis', 'Análisis de Imagen'), ('text_rewrite', 'Reescritura de Texto'), ('cause_suggestion', 'Sugerencia de Causas')], help_text='Tipo de análisis', max_length=50)),
                ('tokens_used', models.IntegerField(help_text='Tokens utilizados')),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=4, help_text='Costo estimado en USD', max_digits=10, null=True)),
                ('success', models.BooleanField(default=True, help_text='Indica si la operación fue exitosa')),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si la operación falló')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(help_text='Proveedor de IA utilizado', on_delete=django.db.models.deletion.CASCADE, to='ai_orchestrator.aiprovider')),
            ],
            options={
                'verbose_name': 'Log de Uso de IA',
                'verbose_name_plural': 'Logs de Uso de IA',
                'db_table': 'ai_usage_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('image_caption', 'Descripción de Imagen'), ('image_analysis', 'Análisis de Imagen'), ('text_rewrite', 'Reescritura de Texto'), ('cause_suggestion', 'Sugerencia de Causas')], help_text='Tipo de análisis realizado', max_length=50)),
                ('input_data', models.JSONField(help_text='Datos de entrada para el análisis')),
                ('output_data', models.JSONField(help_text='Resultados del análisis')),
                ('confidence_score', models.FloatField(blank=True, help_text='Puntuación de confianza (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('tokens_used', models.IntegerField(default=0, help_text='Tokens utilizados en el análisis')),
                ('processing_time', models.FloatField(blank=True, help_text='Tiempo de procesamiento en segundos', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si el análisis falló')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider_used', models.ForeignKey(blank=True, help_text='Proveedor de IA utilizado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_orchestrator.aiprovider')),
            ],
            options={
                'verbose_name': 'Análisis de IA',
                'verbose_name_plural': 'Análisis de IA',
                'db_table': 'ai_analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
