# Generated by Django 4.2.7 on 2026-03-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprovider',
            name='name',
            field=models.CharField(choices=[('google', 'Google Gemini'), ('local', 'Modelo Local (Ollama)')], help_text='Nombre del proveedor de IA', max_length=50, unique=True),
        ),
    ]
