# Generated by Django 4.2.7 on 2026-04-24 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookendpoint',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_webhook_endpoints', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='integrationtemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_integration_templates', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='integrationtemplate',
            name='source_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_templates', to='integrations.externalsystem', verbose_name='Sistema Origen'),
        ),
        migrations.AddField(
            model_name='integrationtemplate',
            name='target_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_templates', to='integrations.externalsystem', verbose_name='Sistema Destino'),
        ),
        migrations.AddField(
            model_name='integrationlog',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integrations.integrationinstance', verbose_name='Instancia'),
        ),
        migrations.AddField(
            model_name='integrationinstance',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_integrations', to=settings.AUTH_USER_MODEL, verbose_name='Completado por'),
        ),
        migrations.AddField(
            model_name='integrationinstance',
            name='related_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.document', verbose_name='Documento Relacionado'),
        ),
        migrations.AddField(
            model_name='integrationinstance',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Relacionado'),
        ),
        migrations.AddField(
            model_name='integrationinstance',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_integrations', to=settings.AUTH_USER_MODEL, verbose_name='Iniciado por'),
        ),
        migrations.AddField(
            model_name='integrationinstance',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='integrations.integrationtemplate', verbose_name='Plantilla'),
        ),
        migrations.AddField(
            model_name='externalsystem',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_external_systems', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
    ]
