# Generated by Django 4.2.7 on 2026-04-24 12:51

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del documento', max_length=200)),
                ('filename', models.CharField(blank=True, help_text='Nombre del archivo', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Descripción del documento')),
                ('document_type', models.CharField(choices=[('plantilla', 'Plantilla'), ('oficial', 'Documento Oficial'), ('borrador', 'Borrador'), ('visit_attachment', 'Adjunto de Visita')], default='oficial', help_text='Tipo de documento', max_length=30)),
                ('version', models.IntegerField(default=1, help_text='Versión del documento')),
                ('docx_path', models.CharField(blank=True, help_text='Ruta del archivo .docx', max_length=500)),
                ('pdf_path', models.CharField(blank=True, help_text='Ruta del archivo .pdf', max_length=500)),
                ('file_path', models.CharField(blank=True, help_text='Ruta del archivo adjunto', max_length=500)),
                ('size', models.BigIntegerField(default=0, help_text='Tamaño del archivo en bytes')),
                ('content_html', models.TextField(blank=True, help_text='Contenido HTML del documento (para edición)')),
                ('placeholders_data', models.JSONField(default=dict, help_text='Datos utilizados para reemplazar placeholders')),
                ('notes', models.TextField(blank=True, help_text='Notas sobre el documento')),
                ('is_final', models.BooleanField(default=False, help_text='Indica si es la versión final del documento')),
                ('is_public', models.BooleanField(default=False, help_text='Indica si el documento es público')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('visit_report', 'Reporte de Visita')], max_length=20, verbose_name='Tipo de Documento')),
                ('document_id', models.PositiveIntegerField(verbose_name='ID del Documento')),
                ('file', models.FileField(upload_to=apps.documents.models.get_attachment_upload_path, verbose_name='Archivo')),
                ('filename', models.CharField(max_length=255, verbose_name='Nombre del Archivo')),
                ('file_type', models.CharField(max_length=50, verbose_name='Tipo de Archivo')),
                ('file_size', models.PositiveIntegerField(verbose_name='Tamaño del Archivo')),
                ('section', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sección del Documento')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Descripción')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
            ],
            options={
                'verbose_name': 'Archivo Adjunto',
                'verbose_name_plural': 'Archivos Adjuntos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_format', models.CharField(help_text='Formato de origen', max_length=10)),
                ('target_format', models.CharField(help_text='Formato de destino', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', help_text='Estado de la conversión', max_length=20)),
                ('source_file_path', models.CharField(default='', help_text='Ruta del archivo de origen', max_length=500)),
                ('target_file_path', models.CharField(blank=True, default='', help_text='Ruta del archivo de destino', max_length=500)),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si la conversión falló')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Conversión de Documento',
                'verbose_name_plural': 'Conversiones de Documentos',
                'db_table': 'document_conversions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la plantilla', max_length=200)),
                ('template_type', models.CharField(choices=[('cliente_informe', 'Informe para Cliente'), ('proveedor_carta', 'Carta para Proveedor'), ('lab_report', 'Reporte de Laboratorio'), ('tecnico_informe', 'Informe Técnico')], help_text='Tipo de plantilla', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Descripción de la plantilla')),
                ('docx_template_path', models.CharField(help_text='Ruta del archivo .docx de la plantilla', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la plantilla está activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Documento',
                'verbose_name_plural': 'Plantillas de Documentos',
                'db_table': 'document_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(help_text='Número de versión')),
                ('docx_path', models.CharField(help_text='Ruta del archivo .docx de esta versión', max_length=500)),
                ('pdf_path', models.CharField(blank=True, help_text='Ruta del archivo .pdf de esta versión', max_length=500)),
                ('content_html', models.TextField(blank=True, help_text='Contenido HTML de esta versión')),
                ('change_notes', models.TextField(blank=True, help_text='Notas sobre los cambios en esta versión')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Versión de Documento',
                'verbose_name_plural': 'Versiones de Documentos',
                'db_table': 'document_versions',
                'ordering': ['-version_number'],
            },
        ),
    ]
