# Generated by Django 4.2.7 on 2025-12-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('pending_review', 'Pendiente de Revisión'), ('approved', 'Aprobado'), ('sent', 'Enviado'), ('closed', 'Cerrado')], db_index=True, default='draft', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='qualityreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='qualityreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('review', 'En Revisión'), ('approved', 'Aprobado'), ('sent', 'Enviado'), ('closed', 'Cerrado')], db_index=True, default='draft', help_text='Estado del reporte', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplierreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('pending_review', 'Pendiente de Revisión'), ('approved', 'Aprobado'), ('sent', 'Enviado'), ('closed', 'Cerrado')], db_index=True, default='draft', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('pending_review', 'Pendiente de Revisión'), ('approved', 'Aprobado'), ('sent', 'Enviado'), ('closed', 'Cerrado')], db_index=True, default='draft', max_length=20, verbose_name='Estado'),
        ),
    ]
