# Generated by Django 4.2.7 on 2026-01-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_labreport_created_at_alter_labreport_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción del documento'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_path',
            field=models.CharField(blank=True, help_text='Ruta del archivo adjunto', max_length=500),
        ),
        migrations.AddField(
            model_name='document',
            name='filename',
            field=models.CharField(blank=True, help_text='Nombre del archivo', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Indica si el documento es público'),
        ),
        migrations.AddField(
            model_name='document',
            name='size',
            field=models.BigIntegerField(default=0, help_text='Tamaño del archivo en bytes'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('plantilla', 'Plantilla'), ('oficial', 'Documento Oficial'), ('borrador', 'Borrador'), ('incident_attachment', 'Adjunto de Incidencia')], default='oficial', help_text='Tipo de documento', max_length=30),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('pending_review', 'Pendiente de Revisión'), ('approved', 'Aprobado'), ('sent', 'Enviado'), ('waiting_response', 'Esperando Respuesta'), ('closed', 'Cerrado')], db_index=True, default='draft', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='supplierreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('pending_review', 'Pendiente de Revisión'), ('approved', 'Aprobado'), ('sent', 'Enviado'), ('waiting_response', 'Esperando Respuesta'), ('closed', 'Cerrado')], db_index=True, default='draft', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('pending_review', 'Pendiente de Revisión'), ('approved', 'Aprobado'), ('sent', 'Enviado'), ('waiting_response', 'Esperando Respuesta'), ('closed', 'Cerrado')], db_index=True, default='draft', max_length=20, verbose_name='Estado'),
        ),
    ]
