# Generated by Django 4.2.7 on 2026-01-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_description_document_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualityreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('review', 'En Revisión'), ('approved', 'Aprobado'), ('sent', 'Enviado'), ('escalated', 'Escalado'), ('closed', 'Cerrado')], db_index=True, default='draft', help_text='Estado del reporte', max_length=20),
        ),
    ]
