# Generated by Django 4.2.7 on 2026-01-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_qualityreport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentattachment',
            name='document_type',
            field=models.CharField(choices=[('visit_report', 'Reporte de Visita'), ('lab_report', 'Informe de Laboratorio'), ('supplier_report', 'Informe para Proveedor'), ('supplier_response', 'Respuesta del Proveedor'), ('incident_attachment', 'Adjunto de Incidencia')], max_length=20, verbose_name='Tipo de Documento'),
        ),
    ]
