# Generated by Django 4.2.7 on 2026-01-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_documentattachment_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitreport',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronización'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='sap_call_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID Llamada SAP'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='sync_error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Error Sincronización'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='sync_status',
            field=models.CharField(default='pending', max_length=20, verbose_name='Estado Sincronización'),
        ),
    ]
