# Generated by Django 4.2.7 on 2026-01-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_visitreport_last_synced_at_visitreport_sap_call_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitreport',
            name='contact_observations',
            field=models.TextField(blank=True, verbose_name='Observaciones de Contacto'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='fax',
            field=models.CharField(blank=True, max_length=20, verbose_name='Fax'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='management_manager',
            field=models.CharField(blank=True, max_length=100, verbose_name='Encargado de Gestión'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='materials_data',
            field=models.JSONField(blank=True, default=list, verbose_name='Tabla de Materiales'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='professional_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Profesional de Obra'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='quality_manager',
            field=models.CharField(blank=True, max_length=100, verbose_name='Encargado de Calidad'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='technical_inspector',
            field=models.CharField(blank=True, max_length=100, verbose_name='Inspector Técnico de Obra'),
        ),
    ]
