# Generated by Django 4.2.7 on 2026-01-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_visitreport_contact_observations_visitreport_fax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitreport',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='visit_reports/pdfs/%Y/%m/', verbose_name='PDF del Reporte'),
        ),
    ]
