# Generated by Django 4.2.7 on 2026-02-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_visitreport_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitreport',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='client_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Cliente'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='client_rut',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Cliente'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='commune',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comuna'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='project_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID del Proyecto'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='project_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Proyecto'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='salesperson',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='technician',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Técnico'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='visit_reason',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo de la Visita'),
        ),
    ]
