# Generated by Django 4.2.7 on 2026-02-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_visitreport_address_alter_visitreport_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Informe para Proveedor', 'verbose_name_plural': 'Informes para Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='visitreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Reporte de Visita', 'verbose_name_plural': 'Reportes de Visita'},
        ),
        migrations.AddField(
            model_name='documentattachment',
            name='section',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sección del Documento'),
        ),
        migrations.AlterField(
            model_name='documentattachment',
            name='document_type',
            field=models.CharField(choices=[('visit_report', 'Reporte de Visita'), ('lab_report', 'Informe de Laboratorio'), ('supplier_report', 'Informe para Proveedor'), ('supplier_response', 'Respuesta del Proveedor'), ('incident_attachment', 'Adjunto de Incidencia'), ('quality_report', 'Reporte de Calidad')], max_length=20, verbose_name='Tipo de Documento'),
        ),
    ]
