# Generated by Django 4.2.7 on 2026-03-20 15:43

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_alter_supplierreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitreport',
            name='technician_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Técnico SAP'),
        ),
        migrations.AlterField(
            model_name='documentattachment',
            name='file',
            field=models.FileField(upload_to=apps.documents.models.get_attachment_upload_path, verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.documents.models.get_visit_report_pdf_path, verbose_name='PDF del Reporte'),
        ),
    ]
